// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240410074018_StoreItem-DiscountAdded")]
    partial class StoreItemDiscountAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreItemId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StoreItemId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SalesRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuantitySold = 47,
                            SaleDate = new DateTime(2023, 12, 7, 1, 19, 4, 173, DateTimeKind.Local).AddTicks(5162),
                            StoreItemId = 13,
                            SupplierId = 2,
                            TotalAmount = 388.086019790771180m
                        },
                        new
                        {
                            Id = 2,
                            QuantitySold = 17,
                            SaleDate = new DateTime(2023, 5, 20, 7, 10, 6, 830, DateTimeKind.Local).AddTicks(7257),
                            StoreItemId = 39,
                            SupplierId = 5,
                            TotalAmount = 492.673055777639720m
                        },
                        new
                        {
                            Id = 3,
                            QuantitySold = 87,
                            SaleDate = new DateTime(2023, 11, 1, 13, 1, 9, 487, DateTimeKind.Local).AddTicks(8879),
                            StoreItemId = 15,
                            SupplierId = 7,
                            TotalAmount = 107.260091764507770m
                        },
                        new
                        {
                            Id = 4,
                            QuantitySold = 57,
                            SaleDate = new DateTime(2023, 4, 14, 18, 52, 12, 145, DateTimeKind.Local).AddTicks(526),
                            StoreItemId = 41,
                            SupplierId = 10,
                            TotalAmount = 211.847127751376310m
                        },
                        new
                        {
                            Id = 5,
                            QuantitySold = 27,
                            SaleDate = new DateTime(2023, 9, 27, 0, 43, 14, 802, DateTimeKind.Local).AddTicks(2142),
                            StoreItemId = 17,
                            SupplierId = 3,
                            TotalAmount = 316.434163738244360m
                        },
                        new
                        {
                            Id = 6,
                            QuantitySold = 97,
                            SaleDate = new DateTime(2024, 3, 10, 6, 34, 17, 459, DateTimeKind.Local).AddTicks(3757),
                            StoreItemId = 44,
                            SupplierId = 6,
                            TotalAmount = 421.021199725112410m
                        },
                        new
                        {
                            Id = 7,
                            QuantitySold = 67,
                            SaleDate = new DateTime(2023, 8, 22, 12, 25, 20, 116, DateTimeKind.Local).AddTicks(5371),
                            StoreItemId = 20,
                            SupplierId = 9,
                            TotalAmount = 35.6082357119807050m
                        },
                        new
                        {
                            Id = 8,
                            QuantitySold = 36,
                            SaleDate = new DateTime(2024, 2, 3, 18, 16, 22, 773, DateTimeKind.Local).AddTicks(6984),
                            StoreItemId = 46,
                            SupplierId = 2,
                            TotalAmount = 140.1952716988490m
                        },
                        new
                        {
                            Id = 9,
                            QuantitySold = 6,
                            SaleDate = new DateTime(2023, 7, 18, 0, 7, 25, 430, DateTimeKind.Local).AddTicks(8597),
                            StoreItemId = 22,
                            SupplierId = 5,
                            TotalAmount = 244.782307685717050m
                        },
                        new
                        {
                            Id = 10,
                            QuantitySold = 76,
                            SaleDate = new DateTime(2023, 12, 30, 5, 58, 28, 88, DateTimeKind.Local).AddTicks(212),
                            StoreItemId = 48,
                            SupplierId = 8,
                            TotalAmount = 349.36934367258510m
                        },
                        new
                        {
                            Id = 11,
                            QuantitySold = 46,
                            SaleDate = new DateTime(2023, 6, 12, 11, 49, 30, 745, DateTimeKind.Local).AddTicks(1851),
                            StoreItemId = 24,
                            SupplierId = 1,
                            TotalAmount = 453.956379659453640m
                        },
                        new
                        {
                            Id = 12,
                            QuantitySold = 16,
                            SaleDate = new DateTime(2023, 11, 24, 17, 40, 33, 402, DateTimeKind.Local).AddTicks(3468),
                            StoreItemId = 50,
                            SupplierId = 4,
                            TotalAmount = 68.543415646321690m
                        },
                        new
                        {
                            Id = 13,
                            QuantitySold = 86,
                            SaleDate = new DateTime(2023, 5, 7, 23, 31, 36, 59, DateTimeKind.Local).AddTicks(5081),
                            StoreItemId = 26,
                            SupplierId = 7,
                            TotalAmount = 173.130451633190230m
                        },
                        new
                        {
                            Id = 14,
                            QuantitySold = 56,
                            SaleDate = new DateTime(2023, 10, 20, 5, 22, 38, 716, DateTimeKind.Local).AddTicks(6696),
                            StoreItemId = 3,
                            SupplierId = 10,
                            TotalAmount = 277.717487620058280m
                        },
                        new
                        {
                            Id = 15,
                            QuantitySold = 26,
                            SaleDate = new DateTime(2024, 4, 2, 11, 13, 41, 373, DateTimeKind.Local).AddTicks(8310),
                            StoreItemId = 29,
                            SupplierId = 3,
                            TotalAmount = 382.304523606926330m
                        },
                        new
                        {
                            Id = 16,
                            QuantitySold = 96,
                            SaleDate = new DateTime(2023, 9, 14, 17, 4, 44, 30, DateTimeKind.Local).AddTicks(9924),
                            StoreItemId = 5,
                            SupplierId = 6,
                            TotalAmount = 486.891559593794380m
                        },
                        new
                        {
                            Id = 17,
                            QuantitySold = 66,
                            SaleDate = new DateTime(2024, 2, 26, 22, 55, 46, 688, DateTimeKind.Local).AddTicks(1537),
                            StoreItemId = 31,
                            SupplierId = 9,
                            TotalAmount = 101.478595580662920m
                        },
                        new
                        {
                            Id = 18,
                            QuantitySold = 35,
                            SaleDate = new DateTime(2023, 8, 10, 4, 46, 49, 345, DateTimeKind.Local).AddTicks(3150),
                            StoreItemId = 7,
                            SupplierId = 1,
                            TotalAmount = 206.065631567530970m
                        },
                        new
                        {
                            Id = 19,
                            QuantitySold = 5,
                            SaleDate = new DateTime(2024, 1, 22, 10, 37, 52, 2, DateTimeKind.Local).AddTicks(4810),
                            StoreItemId = 33,
                            SupplierId = 4,
                            TotalAmount = 310.652667554399510m
                        },
                        new
                        {
                            Id = 20,
                            QuantitySold = 75,
                            SaleDate = new DateTime(2023, 7, 5, 16, 28, 54, 659, DateTimeKind.Local).AddTicks(6423),
                            StoreItemId = 9,
                            SupplierId = 7,
                            TotalAmount = 415.239703541267560m
                        },
                        new
                        {
                            Id = 21,
                            QuantitySold = 45,
                            SaleDate = new DateTime(2023, 12, 17, 22, 19, 57, 316, DateTimeKind.Local).AddTicks(8037),
                            StoreItemId = 35,
                            SupplierId = 10,
                            TotalAmount = 29.8267395281357570m
                        },
                        new
                        {
                            Id = 22,
                            QuantitySold = 15,
                            SaleDate = new DateTime(2023, 5, 31, 4, 10, 59, 973, DateTimeKind.Local).AddTicks(9649),
                            StoreItemId = 11,
                            SupplierId = 3,
                            TotalAmount = 134.413775515004150m
                        },
                        new
                        {
                            Id = 23,
                            QuantitySold = 85,
                            SaleDate = new DateTime(2023, 11, 12, 10, 2, 2, 631, DateTimeKind.Local).AddTicks(1264),
                            StoreItemId = 38,
                            SupplierId = 6,
                            TotalAmount = 239.00081150187220m
                        },
                        new
                        {
                            Id = 24,
                            QuantitySold = 55,
                            SaleDate = new DateTime(2023, 4, 25, 15, 53, 5, 288, DateTimeKind.Local).AddTicks(2877),
                            StoreItemId = 14,
                            SupplierId = 9,
                            TotalAmount = 343.587847488740250m
                        },
                        new
                        {
                            Id = 25,
                            QuantitySold = 25,
                            SaleDate = new DateTime(2023, 10, 7, 21, 44, 7, 945, DateTimeKind.Local).AddTicks(4491),
                            StoreItemId = 40,
                            SupplierId = 2,
                            TotalAmount = 448.174883475608790m
                        },
                        new
                        {
                            Id = 26,
                            QuantitySold = 95,
                            SaleDate = new DateTime(2024, 3, 21, 3, 35, 10, 602, DateTimeKind.Local).AddTicks(6130),
                            StoreItemId = 16,
                            SupplierId = 5,
                            TotalAmount = 62.761919462476840m
                        },
                        new
                        {
                            Id = 27,
                            QuantitySold = 65,
                            SaleDate = new DateTime(2023, 9, 2, 9, 26, 13, 259, DateTimeKind.Local).AddTicks(7745),
                            StoreItemId = 42,
                            SupplierId = 8,
                            TotalAmount = 167.348955449344890m
                        },
                        new
                        {
                            Id = 28,
                            QuantitySold = 34,
                            SaleDate = new DateTime(2024, 2, 14, 15, 17, 15, 916, DateTimeKind.Local).AddTicks(9364),
                            StoreItemId = 18,
                            SupplierId = 1,
                            TotalAmount = 271.935991436213430m
                        },
                        new
                        {
                            Id = 29,
                            QuantitySold = 4,
                            SaleDate = new DateTime(2023, 7, 28, 21, 8, 18, 574, DateTimeKind.Local).AddTicks(976),
                            StoreItemId = 44,
                            SupplierId = 4,
                            TotalAmount = 376.523027423081480m
                        },
                        new
                        {
                            Id = 30,
                            QuantitySold = 74,
                            SaleDate = new DateTime(2024, 1, 10, 2, 59, 21, 231, DateTimeKind.Local).AddTicks(2590),
                            StoreItemId = 20,
                            SupplierId = 7,
                            TotalAmount = 481.110063409949530m
                        },
                        new
                        {
                            Id = 31,
                            QuantitySold = 44,
                            SaleDate = new DateTime(2023, 6, 23, 8, 50, 23, 888, DateTimeKind.Local).AddTicks(4202),
                            StoreItemId = 47,
                            SupplierId = 10,
                            TotalAmount = 95.697099396818070m
                        },
                        new
                        {
                            Id = 32,
                            QuantitySold = 14,
                            SaleDate = new DateTime(2023, 12, 5, 14, 41, 26, 545, DateTimeKind.Local).AddTicks(5818),
                            StoreItemId = 23,
                            SupplierId = 3,
                            TotalAmount = 200.284135383686120m
                        },
                        new
                        {
                            Id = 33,
                            QuantitySold = 84,
                            SaleDate = new DateTime(2023, 5, 18, 20, 32, 29, 202, DateTimeKind.Local).AddTicks(7431),
                            StoreItemId = 49,
                            SupplierId = 6,
                            TotalAmount = 304.871171370554170m
                        },
                        new
                        {
                            Id = 34,
                            QuantitySold = 54,
                            SaleDate = new DateTime(2023, 10, 31, 2, 23, 31, 859, DateTimeKind.Local).AddTicks(9073),
                            StoreItemId = 25,
                            SupplierId = 8,
                            TotalAmount = 409.458207357422710m
                        },
                        new
                        {
                            Id = 35,
                            QuantitySold = 24,
                            SaleDate = new DateTime(2023, 4, 13, 8, 14, 34, 517, DateTimeKind.Local).AddTicks(685),
                            StoreItemId = 1,
                            SupplierId = 1,
                            TotalAmount = 24.045243344290760m
                        },
                        new
                        {
                            Id = 36,
                            QuantitySold = 94,
                            SaleDate = new DateTime(2023, 9, 25, 14, 5, 37, 174, DateTimeKind.Local).AddTicks(2299),
                            StoreItemId = 27,
                            SupplierId = 4,
                            TotalAmount = 128.632279331158810m
                        },
                        new
                        {
                            Id = 37,
                            QuantitySold = 64,
                            SaleDate = new DateTime(2024, 3, 8, 19, 56, 39, 831, DateTimeKind.Local).AddTicks(3914),
                            StoreItemId = 3,
                            SupplierId = 7,
                            TotalAmount = 233.219315318027350m
                        },
                        new
                        {
                            Id = 38,
                            QuantitySold = 33,
                            SaleDate = new DateTime(2023, 8, 21, 1, 47, 42, 488, DateTimeKind.Local).AddTicks(5528),
                            StoreItemId = 29,
                            SupplierId = 10,
                            TotalAmount = 337.80635130489540m
                        },
                        new
                        {
                            Id = 39,
                            QuantitySold = 3,
                            SaleDate = new DateTime(2024, 2, 2, 7, 38, 45, 145, DateTimeKind.Local).AddTicks(7142),
                            StoreItemId = 6,
                            SupplierId = 3,
                            TotalAmount = 442.393387291763450m
                        },
                        new
                        {
                            Id = 40,
                            QuantitySold = 73,
                            SaleDate = new DateTime(2023, 7, 16, 13, 29, 47, 802, DateTimeKind.Local).AddTicks(8755),
                            StoreItemId = 32,
                            SupplierId = 6,
                            TotalAmount = 56.9804232786318430m
                        },
                        new
                        {
                            Id = 41,
                            QuantitySold = 43,
                            SaleDate = new DateTime(2023, 12, 28, 19, 20, 50, 460, DateTimeKind.Local).AddTicks(397),
                            StoreItemId = 8,
                            SupplierId = 9,
                            TotalAmount = 161.567459265500040m
                        },
                        new
                        {
                            Id = 42,
                            QuantitySold = 13,
                            SaleDate = new DateTime(2023, 6, 11, 1, 11, 53, 117, DateTimeKind.Local).AddTicks(2011),
                            StoreItemId = 34,
                            SupplierId = 2,
                            TotalAmount = 266.154495252368090m
                        },
                        new
                        {
                            Id = 43,
                            QuantitySold = 83,
                            SaleDate = new DateTime(2023, 11, 23, 7, 2, 55, 774, DateTimeKind.Local).AddTicks(3627),
                            StoreItemId = 10,
                            SupplierId = 5,
                            TotalAmount = 370.741531239236630m
                        },
                        new
                        {
                            Id = 44,
                            QuantitySold = 53,
                            SaleDate = new DateTime(2023, 5, 6, 12, 53, 58, 431, DateTimeKind.Local).AddTicks(5239),
                            StoreItemId = 36,
                            SupplierId = 8,
                            TotalAmount = 475.328567226104680m
                        },
                        new
                        {
                            Id = 45,
                            QuantitySold = 23,
                            SaleDate = new DateTime(2023, 10, 18, 18, 45, 1, 88, DateTimeKind.Local).AddTicks(6852),
                            StoreItemId = 12,
                            SupplierId = 1,
                            TotalAmount = 89.915603212972730m
                        },
                        new
                        {
                            Id = 46,
                            QuantitySold = 93,
                            SaleDate = new DateTime(2024, 4, 1, 0, 36, 3, 745, DateTimeKind.Local).AddTicks(8467),
                            StoreItemId = 38,
                            SupplierId = 4,
                            TotalAmount = 194.502639199841270m
                        },
                        new
                        {
                            Id = 47,
                            QuantitySold = 63,
                            SaleDate = new DateTime(2023, 9, 13, 6, 27, 6, 403, DateTimeKind.Local).AddTicks(81),
                            StoreItemId = 15,
                            SupplierId = 7,
                            TotalAmount = 299.089675186709320m
                        },
                        new
                        {
                            Id = 48,
                            QuantitySold = 32,
                            SaleDate = new DateTime(2024, 2, 25, 12, 18, 9, 60, DateTimeKind.Local).AddTicks(1695),
                            StoreItemId = 41,
                            SupplierId = 10,
                            TotalAmount = 403.676711173577860m
                        },
                        new
                        {
                            Id = 49,
                            QuantitySold = 2,
                            SaleDate = new DateTime(2023, 8, 8, 18, 9, 11, 717, DateTimeKind.Local).AddTicks(3333),
                            StoreItemId = 17,
                            SupplierId = 2,
                            TotalAmount = 18.2637471604457630m
                        },
                        new
                        {
                            Id = 50,
                            QuantitySold = 72,
                            SaleDate = new DateTime(2024, 1, 21, 0, 0, 14, 374, DateTimeKind.Local).AddTicks(4949),
                            StoreItemId = 43,
                            SupplierId = 5,
                            TotalAmount = 122.850783147313960m
                        });
                });

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "aut",
                            Discount = 20,
                            Name = "Bike",
                            Price = 1.771604122021982m,
                            Quantity = 234
                        },
                        new
                        {
                            Id = 2,
                            Description = "ea",
                            Discount = 3,
                            Name = "Cheese",
                            Price = 1.985047052607428m,
                            Quantity = 83
                        },
                        new
                        {
                            Id = 3,
                            Description = "optio",
                            Discount = 17,
                            Name = "Gloves",
                            Price = 1.198489983192873m,
                            Quantity = 433
                        },
                        new
                        {
                            Id = 4,
                            Description = "doloribus",
                            Discount = 0,
                            Name = "Bacon",
                            Price = 1.411932913778319m,
                            Quantity = 282
                        },
                        new
                        {
                            Id = 5,
                            Description = "veniam",
                            Discount = 14,
                            Name = "Pants",
                            Price = 1.625375844363764m,
                            Quantity = 132
                        },
                        new
                        {
                            Id = 6,
                            Description = "in",
                            Discount = 28,
                            Name = "Pizza",
                            Price = 1.838818774949209m,
                            Quantity = 481
                        },
                        new
                        {
                            Id = 7,
                            Description = "accusamus",
                            Discount = 11,
                            Name = "Shirt",
                            Price = 1.0522617055346545m,
                            Quantity = 331
                        },
                        new
                        {
                            Id = 8,
                            Description = "dolorem",
                            Discount = 25,
                            Name = "Salad",
                            Price = 1.2657046361201m,
                            Quantity = 180
                        },
                        new
                        {
                            Id = 9,
                            Description = "praesentium",
                            Discount = 8,
                            Name = "Table",
                            Price = 1.479147566705545m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            Description = "facere",
                            Discount = 22,
                            Name = "Sausages",
                            Price = 1.69259049729099m,
                            Quantity = 379
                        },
                        new
                        {
                            Id = 11,
                            Description = "quae",
                            Discount = 5,
                            Name = "Shoes",
                            Price = 1.906033427876436m,
                            Quantity = 229
                        },
                        new
                        {
                            Id = 12,
                            Description = "laboriosam",
                            Discount = 19,
                            Name = "Chips",
                            Price = 1.119476358461881m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 13,
                            Description = "harum",
                            Discount = 2,
                            Name = "Hat",
                            Price = 1.332919289047327m,
                            Quantity = 428
                        },
                        new
                        {
                            Id = 14,
                            Description = "molestiae",
                            Discount = 16,
                            Name = "Chair",
                            Price = 1.546362219632772m,
                            Quantity = 277
                        },
                        new
                        {
                            Id = 15,
                            Description = "eius",
                            Discount = 30,
                            Name = "Towels",
                            Price = 1.759805150218217m,
                            Quantity = 127
                        },
                        new
                        {
                            Id = 16,
                            Description = "excepturi",
                            Discount = 13,
                            Name = "Computer",
                            Price = 1.973248080803662m,
                            Quantity = 476
                        },
                        new
                        {
                            Id = 17,
                            Description = "aut",
                            Discount = 27,
                            Name = "Soap",
                            Price = 1.186691011389108m,
                            Quantity = 326
                        },
                        new
                        {
                            Id = 18,
                            Description = "aspernatur",
                            Discount = 10,
                            Name = "Keyboard",
                            Price = 1.400133941974553m,
                            Quantity = 175
                        },
                        new
                        {
                            Id = 19,
                            Description = "reprehenderit",
                            Discount = 24,
                            Name = "Tuna",
                            Price = 1.613576872559999m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 20,
                            Description = "nobis",
                            Discount = 7,
                            Name = "Mouse",
                            Price = 1.827019803145444m,
                            Quantity = 374
                        },
                        new
                        {
                            Id = 21,
                            Description = "reiciendis",
                            Discount = 21,
                            Name = "Chicken",
                            Price = 1.0404627337308893m,
                            Quantity = 224
                        },
                        new
                        {
                            Id = 22,
                            Description = "enim",
                            Discount = 4,
                            Name = "Bike",
                            Price = 1.253905664316335m,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 23,
                            Description = "error",
                            Discount = 18,
                            Name = "Fish",
                            Price = 1.46734859490178m,
                            Quantity = 423
                        },
                        new
                        {
                            Id = 24,
                            Description = "vero",
                            Discount = 1,
                            Name = "Ball",
                            Price = 1.680791525487225m,
                            Quantity = 272
                        },
                        new
                        {
                            Id = 25,
                            Description = "sequi",
                            Discount = 15,
                            Name = "Cheese",
                            Price = 1.894234456072671m,
                            Quantity = 122
                        },
                        new
                        {
                            Id = 26,
                            Description = "ducimus",
                            Discount = 29,
                            Name = "Gloves",
                            Price = 1.107677386658116m,
                            Quantity = 471
                        },
                        new
                        {
                            Id = 27,
                            Description = "quod",
                            Discount = 12,
                            Name = "Bacon",
                            Price = 1.321120317243561m,
                            Quantity = 321
                        },
                        new
                        {
                            Id = 28,
                            Description = "aperiam",
                            Discount = 26,
                            Name = "Pants",
                            Price = 1.534563247829007m,
                            Quantity = 170
                        },
                        new
                        {
                            Id = 29,
                            Description = "voluptas",
                            Discount = 9,
                            Name = "Salad",
                            Price = 1.748006178414452m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 30,
                            Description = "dolorum",
                            Discount = 23,
                            Name = "Shirt",
                            Price = 1.961449108999897m,
                            Quantity = 369
                        },
                        new
                        {
                            Id = 31,
                            Description = "repudiandae",
                            Discount = 6,
                            Name = "Sausages",
                            Price = 1.174892039585343m,
                            Quantity = 219
                        },
                        new
                        {
                            Id = 32,
                            Description = "quia",
                            Discount = 20,
                            Name = "Table",
                            Price = 1.388334970170788m,
                            Quantity = 68
                        },
                        new
                        {
                            Id = 33,
                            Description = "et",
                            Discount = 3,
                            Name = "Chips",
                            Price = 1.601777900756233m,
                            Quantity = 418
                        },
                        new
                        {
                            Id = 34,
                            Description = "autem",
                            Discount = 17,
                            Name = "Shoes",
                            Price = 1.815220831341679m,
                            Quantity = 267
                        },
                        new
                        {
                            Id = 35,
                            Description = "dicta",
                            Discount = 0,
                            Name = "Chair",
                            Price = 1.028663761927124m,
                            Quantity = 117
                        },
                        new
                        {
                            Id = 36,
                            Description = "vel",
                            Discount = 14,
                            Name = "Hat",
                            Price = 1.242106692512569m,
                            Quantity = 466
                        },
                        new
                        {
                            Id = 37,
                            Description = "tempore",
                            Discount = 28,
                            Name = "Car",
                            Price = 1.455549623098015m,
                            Quantity = 316
                        },
                        new
                        {
                            Id = 38,
                            Description = "delectus",
                            Discount = 11,
                            Name = "Towels",
                            Price = 1.66899255368346m,
                            Quantity = 165
                        },
                        new
                        {
                            Id = 39,
                            Description = "quaerat",
                            Discount = 25,
                            Name = "Computer",
                            Price = 1.882435484268905m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 40,
                            Description = "omnis",
                            Discount = 8,
                            Name = "Soap",
                            Price = 1.0958784148543507m,
                            Quantity = 364
                        },
                        new
                        {
                            Id = 41,
                            Description = "pariatur",
                            Discount = 22,
                            Name = "Keyboard",
                            Price = 1.309321345439796m,
                            Quantity = 214
                        },
                        new
                        {
                            Id = 42,
                            Description = "qui",
                            Discount = 5,
                            Name = "Chicken",
                            Price = 1.522764276025241m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 43,
                            Description = "iusto",
                            Discount = 19,
                            Name = "Mouse",
                            Price = 1.736207206610687m,
                            Quantity = 413
                        },
                        new
                        {
                            Id = 44,
                            Description = "qui",
                            Discount = 2,
                            Name = "Fish",
                            Price = 1.949650137196132m,
                            Quantity = 262
                        },
                        new
                        {
                            Id = 45,
                            Description = "voluptatem",
                            Discount = 16,
                            Name = "Bike",
                            Price = 1.163093067781577m,
                            Quantity = 112
                        },
                        new
                        {
                            Id = 46,
                            Description = "ipsam",
                            Discount = 30,
                            Name = "Cheese",
                            Price = 1.376535998367023m,
                            Quantity = 461
                        },
                        new
                        {
                            Id = 47,
                            Description = "est",
                            Discount = 13,
                            Name = "Ball",
                            Price = 1.589978928952468m,
                            Quantity = 311
                        },
                        new
                        {
                            Id = 48,
                            Description = "ut",
                            Discount = 27,
                            Name = "Bacon",
                            Price = 1.803421859537914m,
                            Quantity = 160
                        },
                        new
                        {
                            Id = 49,
                            Description = "adipisci",
                            Discount = 10,
                            Name = "Gloves",
                            Price = 1.0168647901233587m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 50,
                            Description = "corrupti",
                            Discount = 24,
                            Name = "Pizza",
                            Price = 1.230307720708804m,
                            Quantity = 359
                        });
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullAddress = "779 Grady Plains, East Georgianafort, Chad",
                            IBAN = "HR7643916023",
                            Name = "Brown and Sons"
                        },
                        new
                        {
                            Id = 2,
                            FullAddress = "00337 Feil Row, Schulistfurt, Uganda",
                            IBAN = "HR1384207005",
                            Name = "Jakubowski, Cummerata and Wyman"
                        },
                        new
                        {
                            Id = 3,
                            FullAddress = "74254 Casper Terrace, Port Jacklynport, Malta",
                            IBAN = "HR1512933586",
                            Name = "Predovic Group"
                        },
                        new
                        {
                            Id = 4,
                            FullAddress = "8386 Krajcik Spurs, North Aylin, Haiti",
                            IBAN = "HR0064472535",
                            Name = "Zboncak, Maggio and Jenkins"
                        },
                        new
                        {
                            Id = 5,
                            FullAddress = "8240 Viola Corner, Satterfieldville, Saint Barthelemy",
                            IBAN = "HR6491951930",
                            Name = "Graham - Gislason"
                        },
                        new
                        {
                            Id = 6,
                            FullAddress = "663 Micheal Street, North Edwardbury, Benin",
                            IBAN = "HR9854747175",
                            Name = "Mayert, Windler and Smitham"
                        },
                        new
                        {
                            Id = 7,
                            FullAddress = "807 Quinn Hill, Chanelport, Honduras",
                            IBAN = "HR0360988494",
                            Name = "Swaniawski - Olson"
                        },
                        new
                        {
                            Id = 8,
                            FullAddress = "48838 Verdie Turnpike, New Randy, Niger",
                            IBAN = "HR8544921716",
                            Name = "Cruickshank, Hessel and Gleason"
                        },
                        new
                        {
                            Id = 9,
                            FullAddress = "97005 Oberbrunner Parkways, New Emelyfurt, Eritrea",
                            IBAN = "HR4249905948",
                            Name = "Koch - Beer"
                        },
                        new
                        {
                            Id = 10,
                            FullAddress = "11365 Cleta Village, Vernonmouth, Thailand",
                            IBAN = "HR7234296256",
                            Name = "Rolfson, Rosenbaum and Pouros"
                        });
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierStoreItems");

                    b.HasData(
                        new
                        {
                            StoreId = 6,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 21,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 50,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 15,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 44,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 9,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 38,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 3,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 32,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 47,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 41,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 40,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 34,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 28,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 22,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 16,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 10,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 25,
                            SupplierId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Models.SalesRecord", b =>
                {
                    b.HasOne("Database.Models.StoreItem", "StoreItem")
                        .WithMany()
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.HasOne("Database.Models.StoreItem", "StoreItem")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Supplier", "Supplier")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
