// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240404115332_DataSeeder")]
    partial class DataSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "aut",
                            Name = "Bike",
                            Price = 1.771604122021982m,
                            Quantity = 234
                        },
                        new
                        {
                            Id = 2,
                            Description = "ea",
                            Name = "Cheese",
                            Price = 1.985047052607428m,
                            Quantity = 83
                        },
                        new
                        {
                            Id = 3,
                            Description = "optio",
                            Name = "Gloves",
                            Price = 1.198489983192873m,
                            Quantity = 433
                        },
                        new
                        {
                            Id = 4,
                            Description = "doloribus",
                            Name = "Bacon",
                            Price = 1.411932913778319m,
                            Quantity = 282
                        },
                        new
                        {
                            Id = 5,
                            Description = "veniam",
                            Name = "Pants",
                            Price = 1.625375844363764m,
                            Quantity = 132
                        },
                        new
                        {
                            Id = 6,
                            Description = "in",
                            Name = "Pizza",
                            Price = 1.838818774949209m,
                            Quantity = 481
                        },
                        new
                        {
                            Id = 7,
                            Description = "accusamus",
                            Name = "Shirt",
                            Price = 1.0522617055346545m,
                            Quantity = 331
                        },
                        new
                        {
                            Id = 8,
                            Description = "dolorem",
                            Name = "Salad",
                            Price = 1.2657046361201m,
                            Quantity = 180
                        },
                        new
                        {
                            Id = 9,
                            Description = "praesentium",
                            Name = "Table",
                            Price = 1.479147566705545m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            Description = "facere",
                            Name = "Sausages",
                            Price = 1.69259049729099m,
                            Quantity = 379
                        },
                        new
                        {
                            Id = 11,
                            Description = "quae",
                            Name = "Shoes",
                            Price = 1.906033427876436m,
                            Quantity = 229
                        },
                        new
                        {
                            Id = 12,
                            Description = "laboriosam",
                            Name = "Chips",
                            Price = 1.119476358461881m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 13,
                            Description = "harum",
                            Name = "Hat",
                            Price = 1.332919289047327m,
                            Quantity = 428
                        },
                        new
                        {
                            Id = 14,
                            Description = "molestiae",
                            Name = "Chair",
                            Price = 1.546362219632772m,
                            Quantity = 277
                        },
                        new
                        {
                            Id = 15,
                            Description = "eius",
                            Name = "Towels",
                            Price = 1.759805150218217m,
                            Quantity = 127
                        },
                        new
                        {
                            Id = 16,
                            Description = "excepturi",
                            Name = "Computer",
                            Price = 1.973248080803662m,
                            Quantity = 476
                        },
                        new
                        {
                            Id = 17,
                            Description = "aut",
                            Name = "Soap",
                            Price = 1.186691011389108m,
                            Quantity = 326
                        },
                        new
                        {
                            Id = 18,
                            Description = "aspernatur",
                            Name = "Keyboard",
                            Price = 1.400133941974553m,
                            Quantity = 175
                        },
                        new
                        {
                            Id = 19,
                            Description = "reprehenderit",
                            Name = "Tuna",
                            Price = 1.613576872559999m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 20,
                            Description = "nobis",
                            Name = "Mouse",
                            Price = 1.827019803145444m,
                            Quantity = 374
                        },
                        new
                        {
                            Id = 21,
                            Description = "reiciendis",
                            Name = "Chicken",
                            Price = 1.0404627337308893m,
                            Quantity = 224
                        },
                        new
                        {
                            Id = 22,
                            Description = "enim",
                            Name = "Bike",
                            Price = 1.253905664316335m,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 23,
                            Description = "error",
                            Name = "Fish",
                            Price = 1.46734859490178m,
                            Quantity = 423
                        },
                        new
                        {
                            Id = 24,
                            Description = "vero",
                            Name = "Ball",
                            Price = 1.680791525487225m,
                            Quantity = 272
                        },
                        new
                        {
                            Id = 25,
                            Description = "sequi",
                            Name = "Cheese",
                            Price = 1.894234456072671m,
                            Quantity = 122
                        },
                        new
                        {
                            Id = 26,
                            Description = "ducimus",
                            Name = "Gloves",
                            Price = 1.107677386658116m,
                            Quantity = 471
                        },
                        new
                        {
                            Id = 27,
                            Description = "quod",
                            Name = "Bacon",
                            Price = 1.321120317243561m,
                            Quantity = 321
                        },
                        new
                        {
                            Id = 28,
                            Description = "aperiam",
                            Name = "Pants",
                            Price = 1.534563247829007m,
                            Quantity = 170
                        },
                        new
                        {
                            Id = 29,
                            Description = "voluptas",
                            Name = "Salad",
                            Price = 1.748006178414452m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 30,
                            Description = "dolorum",
                            Name = "Shirt",
                            Price = 1.961449108999897m,
                            Quantity = 369
                        },
                        new
                        {
                            Id = 31,
                            Description = "repudiandae",
                            Name = "Sausages",
                            Price = 1.174892039585343m,
                            Quantity = 219
                        },
                        new
                        {
                            Id = 32,
                            Description = "quia",
                            Name = "Table",
                            Price = 1.388334970170788m,
                            Quantity = 68
                        },
                        new
                        {
                            Id = 33,
                            Description = "et",
                            Name = "Chips",
                            Price = 1.601777900756233m,
                            Quantity = 418
                        },
                        new
                        {
                            Id = 34,
                            Description = "autem",
                            Name = "Shoes",
                            Price = 1.815220831341679m,
                            Quantity = 267
                        },
                        new
                        {
                            Id = 35,
                            Description = "dicta",
                            Name = "Chair",
                            Price = 1.028663761927124m,
                            Quantity = 117
                        },
                        new
                        {
                            Id = 36,
                            Description = "vel",
                            Name = "Hat",
                            Price = 1.242106692512569m,
                            Quantity = 466
                        },
                        new
                        {
                            Id = 37,
                            Description = "tempore",
                            Name = "Car",
                            Price = 1.455549623098015m,
                            Quantity = 316
                        },
                        new
                        {
                            Id = 38,
                            Description = "delectus",
                            Name = "Towels",
                            Price = 1.66899255368346m,
                            Quantity = 165
                        },
                        new
                        {
                            Id = 39,
                            Description = "quaerat",
                            Name = "Computer",
                            Price = 1.882435484268905m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 40,
                            Description = "omnis",
                            Name = "Soap",
                            Price = 1.0958784148543507m,
                            Quantity = 364
                        },
                        new
                        {
                            Id = 41,
                            Description = "pariatur",
                            Name = "Keyboard",
                            Price = 1.309321345439796m,
                            Quantity = 214
                        },
                        new
                        {
                            Id = 42,
                            Description = "qui",
                            Name = "Chicken",
                            Price = 1.522764276025241m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 43,
                            Description = "iusto",
                            Name = "Mouse",
                            Price = 1.736207206610687m,
                            Quantity = 413
                        },
                        new
                        {
                            Id = 44,
                            Description = "qui",
                            Name = "Fish",
                            Price = 1.949650137196132m,
                            Quantity = 262
                        },
                        new
                        {
                            Id = 45,
                            Description = "voluptatem",
                            Name = "Bike",
                            Price = 1.163093067781577m,
                            Quantity = 112
                        },
                        new
                        {
                            Id = 46,
                            Description = "ipsam",
                            Name = "Cheese",
                            Price = 1.376535998367023m,
                            Quantity = 461
                        },
                        new
                        {
                            Id = 47,
                            Description = "est",
                            Name = "Ball",
                            Price = 1.589978928952468m,
                            Quantity = 311
                        },
                        new
                        {
                            Id = 48,
                            Description = "ut",
                            Name = "Bacon",
                            Price = 1.803421859537914m,
                            Quantity = 160
                        },
                        new
                        {
                            Id = 49,
                            Description = "adipisci",
                            Name = "Gloves",
                            Price = 1.0168647901233587m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 50,
                            Description = "corrupti",
                            Name = "Pizza",
                            Price = 1.230307720708804m,
                            Quantity = 359
                        });
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullAddress = "779 Grady Plains, East Georgianafort, Chad",
                            IBAN = "HR7643916023",
                            Name = "Brown and Sons"
                        },
                        new
                        {
                            Id = 2,
                            FullAddress = "00337 Feil Row, Schulistfurt, Uganda",
                            IBAN = "HR1384207005",
                            Name = "Jakubowski, Cummerata and Wyman"
                        },
                        new
                        {
                            Id = 3,
                            FullAddress = "74254 Casper Terrace, Port Jacklynport, Malta",
                            IBAN = "HR1512933586",
                            Name = "Predovic Group"
                        },
                        new
                        {
                            Id = 4,
                            FullAddress = "8386 Krajcik Spurs, North Aylin, Haiti",
                            IBAN = "HR0064472535",
                            Name = "Zboncak, Maggio and Jenkins"
                        },
                        new
                        {
                            Id = 5,
                            FullAddress = "8240 Viola Corner, Satterfieldville, Saint Barthelemy",
                            IBAN = "HR6491951930",
                            Name = "Graham - Gislason"
                        },
                        new
                        {
                            Id = 6,
                            FullAddress = "663 Micheal Street, North Edwardbury, Benin",
                            IBAN = "HR9854747175",
                            Name = "Mayert, Windler and Smitham"
                        },
                        new
                        {
                            Id = 7,
                            FullAddress = "807 Quinn Hill, Chanelport, Honduras",
                            IBAN = "HR0360988494",
                            Name = "Swaniawski - Olson"
                        },
                        new
                        {
                            Id = 8,
                            FullAddress = "48838 Verdie Turnpike, New Randy, Niger",
                            IBAN = "HR8544921716",
                            Name = "Cruickshank, Hessel and Gleason"
                        },
                        new
                        {
                            Id = 9,
                            FullAddress = "97005 Oberbrunner Parkways, New Emelyfurt, Eritrea",
                            IBAN = "HR4249905948",
                            Name = "Koch - Beer"
                        },
                        new
                        {
                            Id = 10,
                            FullAddress = "11365 Cleta Village, Vernonmouth, Thailand",
                            IBAN = "HR7234296256",
                            Name = "Rolfson, Rosenbaum and Pouros"
                        });
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierStoreItems");

                    b.HasData(
                        new
                        {
                            StoreId = 6,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 21,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 50,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 15,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 44,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 9,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 38,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 3,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 32,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 47,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 41,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 40,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 34,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 28,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 22,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 16,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 10,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 25,
                            SupplierId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.HasOne("Database.Models.StoreItem", "StoreItem")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Supplier", "Supplier")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
