// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240409150948_SalesRecord-SupplierAdded")]
    partial class SalesRecordSupplierAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreItemId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StoreItemId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SalesRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuantitySold = 47,
                            SaleDate = new DateTime(2023, 12, 6, 8, 48, 33, 363, DateTimeKind.Local).AddTicks(7109),
                            StoreItemId = 13,
                            SupplierId = 2,
                            TotalAmount = 388.086019790771180m
                        },
                        new
                        {
                            Id = 2,
                            QuantitySold = 17,
                            SaleDate = new DateTime(2023, 5, 19, 14, 39, 36, 20, DateTimeKind.Local).AddTicks(9289),
                            StoreItemId = 39,
                            SupplierId = 5,
                            TotalAmount = 492.673055777639720m
                        },
                        new
                        {
                            Id = 3,
                            QuantitySold = 87,
                            SaleDate = new DateTime(2023, 10, 31, 20, 30, 38, 678, DateTimeKind.Local).AddTicks(907),
                            StoreItemId = 15,
                            SupplierId = 7,
                            TotalAmount = 107.260091764507770m
                        },
                        new
                        {
                            Id = 4,
                            QuantitySold = 57,
                            SaleDate = new DateTime(2023, 4, 14, 2, 21, 41, 335, DateTimeKind.Local).AddTicks(2523),
                            StoreItemId = 41,
                            SupplierId = 10,
                            TotalAmount = 211.847127751376310m
                        },
                        new
                        {
                            Id = 5,
                            QuantitySold = 27,
                            SaleDate = new DateTime(2023, 9, 26, 8, 12, 43, 992, DateTimeKind.Local).AddTicks(4138),
                            StoreItemId = 17,
                            SupplierId = 3,
                            TotalAmount = 316.434163738244360m
                        },
                        new
                        {
                            Id = 6,
                            QuantitySold = 97,
                            SaleDate = new DateTime(2024, 3, 9, 14, 3, 46, 649, DateTimeKind.Local).AddTicks(5753),
                            StoreItemId = 44,
                            SupplierId = 6,
                            TotalAmount = 421.021199725112410m
                        },
                        new
                        {
                            Id = 7,
                            QuantitySold = 67,
                            SaleDate = new DateTime(2023, 8, 21, 19, 54, 49, 306, DateTimeKind.Local).AddTicks(7367),
                            StoreItemId = 20,
                            SupplierId = 9,
                            TotalAmount = 35.6082357119807050m
                        },
                        new
                        {
                            Id = 8,
                            QuantitySold = 36,
                            SaleDate = new DateTime(2024, 2, 3, 1, 45, 51, 963, DateTimeKind.Local).AddTicks(8980),
                            StoreItemId = 46,
                            SupplierId = 2,
                            TotalAmount = 140.1952716988490m
                        },
                        new
                        {
                            Id = 9,
                            QuantitySold = 6,
                            SaleDate = new DateTime(2023, 7, 17, 7, 36, 54, 621, DateTimeKind.Local).AddTicks(623),
                            StoreItemId = 22,
                            SupplierId = 5,
                            TotalAmount = 244.782307685717050m
                        },
                        new
                        {
                            Id = 10,
                            QuantitySold = 76,
                            SaleDate = new DateTime(2023, 12, 29, 13, 27, 57, 278, DateTimeKind.Local).AddTicks(2238),
                            StoreItemId = 48,
                            SupplierId = 8,
                            TotalAmount = 349.36934367258510m
                        },
                        new
                        {
                            Id = 11,
                            QuantitySold = 46,
                            SaleDate = new DateTime(2023, 6, 11, 19, 18, 59, 935, DateTimeKind.Local).AddTicks(3851),
                            StoreItemId = 24,
                            SupplierId = 1,
                            TotalAmount = 453.956379659453640m
                        },
                        new
                        {
                            Id = 12,
                            QuantitySold = 16,
                            SaleDate = new DateTime(2023, 11, 24, 1, 10, 2, 592, DateTimeKind.Local).AddTicks(5467),
                            StoreItemId = 50,
                            SupplierId = 4,
                            TotalAmount = 68.543415646321690m
                        },
                        new
                        {
                            Id = 13,
                            QuantitySold = 86,
                            SaleDate = new DateTime(2023, 5, 7, 7, 1, 5, 249, DateTimeKind.Local).AddTicks(7081),
                            StoreItemId = 26,
                            SupplierId = 7,
                            TotalAmount = 173.130451633190230m
                        },
                        new
                        {
                            Id = 14,
                            QuantitySold = 56,
                            SaleDate = new DateTime(2023, 10, 19, 12, 52, 7, 906, DateTimeKind.Local).AddTicks(8695),
                            StoreItemId = 3,
                            SupplierId = 10,
                            TotalAmount = 277.717487620058280m
                        },
                        new
                        {
                            Id = 15,
                            QuantitySold = 26,
                            SaleDate = new DateTime(2024, 4, 1, 18, 43, 10, 564, DateTimeKind.Local).AddTicks(309),
                            StoreItemId = 29,
                            SupplierId = 3,
                            TotalAmount = 382.304523606926330m
                        },
                        new
                        {
                            Id = 16,
                            QuantitySold = 96,
                            SaleDate = new DateTime(2023, 9, 14, 0, 34, 13, 221, DateTimeKind.Local).AddTicks(1951),
                            StoreItemId = 5,
                            SupplierId = 6,
                            TotalAmount = 486.891559593794380m
                        },
                        new
                        {
                            Id = 17,
                            QuantitySold = 66,
                            SaleDate = new DateTime(2024, 2, 26, 6, 25, 15, 878, DateTimeKind.Local).AddTicks(3563),
                            StoreItemId = 31,
                            SupplierId = 9,
                            TotalAmount = 101.478595580662920m
                        },
                        new
                        {
                            Id = 18,
                            QuantitySold = 35,
                            SaleDate = new DateTime(2023, 8, 9, 12, 16, 18, 535, DateTimeKind.Local).AddTicks(5177),
                            StoreItemId = 7,
                            SupplierId = 1,
                            TotalAmount = 206.065631567530970m
                        },
                        new
                        {
                            Id = 19,
                            QuantitySold = 5,
                            SaleDate = new DateTime(2024, 1, 21, 18, 7, 21, 192, DateTimeKind.Local).AddTicks(6794),
                            StoreItemId = 33,
                            SupplierId = 4,
                            TotalAmount = 310.652667554399510m
                        },
                        new
                        {
                            Id = 20,
                            QuantitySold = 75,
                            SaleDate = new DateTime(2023, 7, 4, 23, 58, 23, 849, DateTimeKind.Local).AddTicks(8407),
                            StoreItemId = 9,
                            SupplierId = 7,
                            TotalAmount = 415.239703541267560m
                        },
                        new
                        {
                            Id = 21,
                            QuantitySold = 45,
                            SaleDate = new DateTime(2023, 12, 17, 5, 49, 26, 507, DateTimeKind.Local).AddTicks(21),
                            StoreItemId = 35,
                            SupplierId = 10,
                            TotalAmount = 29.8267395281357570m
                        },
                        new
                        {
                            Id = 22,
                            QuantitySold = 15,
                            SaleDate = new DateTime(2023, 5, 30, 11, 40, 29, 164, DateTimeKind.Local).AddTicks(1635),
                            StoreItemId = 11,
                            SupplierId = 3,
                            TotalAmount = 134.413775515004150m
                        },
                        new
                        {
                            Id = 23,
                            QuantitySold = 85,
                            SaleDate = new DateTime(2023, 11, 11, 17, 31, 31, 821, DateTimeKind.Local).AddTicks(3250),
                            StoreItemId = 38,
                            SupplierId = 6,
                            TotalAmount = 239.00081150187220m
                        },
                        new
                        {
                            Id = 24,
                            QuantitySold = 55,
                            SaleDate = new DateTime(2023, 4, 24, 23, 22, 34, 478, DateTimeKind.Local).AddTicks(4892),
                            StoreItemId = 14,
                            SupplierId = 9,
                            TotalAmount = 343.587847488740250m
                        },
                        new
                        {
                            Id = 25,
                            QuantitySold = 25,
                            SaleDate = new DateTime(2023, 10, 7, 5, 13, 37, 135, DateTimeKind.Local).AddTicks(6507),
                            StoreItemId = 40,
                            SupplierId = 2,
                            TotalAmount = 448.174883475608790m
                        },
                        new
                        {
                            Id = 26,
                            QuantitySold = 95,
                            SaleDate = new DateTime(2024, 3, 20, 11, 4, 39, 792, DateTimeKind.Local).AddTicks(8119),
                            StoreItemId = 16,
                            SupplierId = 5,
                            TotalAmount = 62.761919462476840m
                        },
                        new
                        {
                            Id = 27,
                            QuantitySold = 65,
                            SaleDate = new DateTime(2023, 9, 1, 16, 55, 42, 449, DateTimeKind.Local).AddTicks(9731),
                            StoreItemId = 42,
                            SupplierId = 8,
                            TotalAmount = 167.348955449344890m
                        },
                        new
                        {
                            Id = 28,
                            QuantitySold = 34,
                            SaleDate = new DateTime(2024, 2, 13, 22, 46, 45, 107, DateTimeKind.Local).AddTicks(1345),
                            StoreItemId = 18,
                            SupplierId = 1,
                            TotalAmount = 271.935991436213430m
                        },
                        new
                        {
                            Id = 29,
                            QuantitySold = 4,
                            SaleDate = new DateTime(2023, 7, 28, 4, 37, 47, 764, DateTimeKind.Local).AddTicks(2957),
                            StoreItemId = 44,
                            SupplierId = 4,
                            TotalAmount = 376.523027423081480m
                        },
                        new
                        {
                            Id = 30,
                            QuantitySold = 74,
                            SaleDate = new DateTime(2024, 1, 9, 10, 28, 50, 421, DateTimeKind.Local).AddTicks(4571),
                            StoreItemId = 20,
                            SupplierId = 7,
                            TotalAmount = 481.110063409949530m
                        },
                        new
                        {
                            Id = 31,
                            QuantitySold = 44,
                            SaleDate = new DateTime(2023, 6, 22, 16, 19, 53, 78, DateTimeKind.Local).AddTicks(6212),
                            StoreItemId = 47,
                            SupplierId = 10,
                            TotalAmount = 95.697099396818070m
                        },
                        new
                        {
                            Id = 32,
                            QuantitySold = 14,
                            SaleDate = new DateTime(2023, 12, 4, 22, 10, 55, 735, DateTimeKind.Local).AddTicks(7827),
                            StoreItemId = 23,
                            SupplierId = 3,
                            TotalAmount = 200.284135383686120m
                        },
                        new
                        {
                            Id = 33,
                            QuantitySold = 84,
                            SaleDate = new DateTime(2023, 5, 18, 4, 1, 58, 392, DateTimeKind.Local).AddTicks(9440),
                            StoreItemId = 49,
                            SupplierId = 6,
                            TotalAmount = 304.871171370554170m
                        },
                        new
                        {
                            Id = 34,
                            QuantitySold = 54,
                            SaleDate = new DateTime(2023, 10, 30, 9, 53, 1, 50, DateTimeKind.Local).AddTicks(1053),
                            StoreItemId = 25,
                            SupplierId = 8,
                            TotalAmount = 409.458207357422710m
                        },
                        new
                        {
                            Id = 35,
                            QuantitySold = 24,
                            SaleDate = new DateTime(2023, 4, 12, 15, 44, 3, 707, DateTimeKind.Local).AddTicks(2665),
                            StoreItemId = 1,
                            SupplierId = 1,
                            TotalAmount = 24.045243344290760m
                        },
                        new
                        {
                            Id = 36,
                            QuantitySold = 94,
                            SaleDate = new DateTime(2023, 9, 24, 21, 35, 6, 364, DateTimeKind.Local).AddTicks(4279),
                            StoreItemId = 27,
                            SupplierId = 4,
                            TotalAmount = 128.632279331158810m
                        },
                        new
                        {
                            Id = 37,
                            QuantitySold = 64,
                            SaleDate = new DateTime(2024, 3, 8, 3, 26, 9, 21, DateTimeKind.Local).AddTicks(5893),
                            StoreItemId = 3,
                            SupplierId = 7,
                            TotalAmount = 233.219315318027350m
                        },
                        new
                        {
                            Id = 38,
                            QuantitySold = 33,
                            SaleDate = new DateTime(2023, 8, 20, 9, 17, 11, 678, DateTimeKind.Local).AddTicks(7506),
                            StoreItemId = 29,
                            SupplierId = 10,
                            TotalAmount = 337.80635130489540m
                        },
                        new
                        {
                            Id = 39,
                            QuantitySold = 3,
                            SaleDate = new DateTime(2024, 2, 1, 15, 8, 14, 335, DateTimeKind.Local).AddTicks(9146),
                            StoreItemId = 6,
                            SupplierId = 3,
                            TotalAmount = 442.393387291763450m
                        },
                        new
                        {
                            Id = 40,
                            QuantitySold = 73,
                            SaleDate = new DateTime(2023, 7, 15, 20, 59, 16, 993, DateTimeKind.Local).AddTicks(759),
                            StoreItemId = 32,
                            SupplierId = 6,
                            TotalAmount = 56.9804232786318430m
                        },
                        new
                        {
                            Id = 41,
                            QuantitySold = 43,
                            SaleDate = new DateTime(2023, 12, 28, 2, 50, 19, 650, DateTimeKind.Local).AddTicks(2374),
                            StoreItemId = 8,
                            SupplierId = 9,
                            TotalAmount = 161.567459265500040m
                        },
                        new
                        {
                            Id = 42,
                            QuantitySold = 13,
                            SaleDate = new DateTime(2023, 6, 10, 8, 41, 22, 307, DateTimeKind.Local).AddTicks(3986),
                            StoreItemId = 34,
                            SupplierId = 2,
                            TotalAmount = 266.154495252368090m
                        },
                        new
                        {
                            Id = 43,
                            QuantitySold = 83,
                            SaleDate = new DateTime(2023, 11, 22, 14, 32, 24, 964, DateTimeKind.Local).AddTicks(5600),
                            StoreItemId = 10,
                            SupplierId = 5,
                            TotalAmount = 370.741531239236630m
                        },
                        new
                        {
                            Id = 44,
                            QuantitySold = 53,
                            SaleDate = new DateTime(2023, 5, 5, 20, 23, 27, 621, DateTimeKind.Local).AddTicks(7214),
                            StoreItemId = 36,
                            SupplierId = 8,
                            TotalAmount = 475.328567226104680m
                        },
                        new
                        {
                            Id = 45,
                            QuantitySold = 23,
                            SaleDate = new DateTime(2023, 10, 18, 2, 14, 30, 278, DateTimeKind.Local).AddTicks(8826),
                            StoreItemId = 12,
                            SupplierId = 1,
                            TotalAmount = 89.915603212972730m
                        },
                        new
                        {
                            Id = 46,
                            QuantitySold = 93,
                            SaleDate = new DateTime(2024, 3, 31, 8, 5, 32, 936, DateTimeKind.Local).AddTicks(467),
                            StoreItemId = 38,
                            SupplierId = 4,
                            TotalAmount = 194.502639199841270m
                        },
                        new
                        {
                            Id = 47,
                            QuantitySold = 63,
                            SaleDate = new DateTime(2023, 9, 12, 13, 56, 35, 593, DateTimeKind.Local).AddTicks(2080),
                            StoreItemId = 15,
                            SupplierId = 7,
                            TotalAmount = 299.089675186709320m
                        },
                        new
                        {
                            Id = 48,
                            QuantitySold = 32,
                            SaleDate = new DateTime(2024, 2, 24, 19, 47, 38, 250, DateTimeKind.Local).AddTicks(3694),
                            StoreItemId = 41,
                            SupplierId = 10,
                            TotalAmount = 403.676711173577860m
                        },
                        new
                        {
                            Id = 49,
                            QuantitySold = 2,
                            SaleDate = new DateTime(2023, 8, 8, 1, 38, 40, 907, DateTimeKind.Local).AddTicks(5307),
                            StoreItemId = 17,
                            SupplierId = 2,
                            TotalAmount = 18.2637471604457630m
                        },
                        new
                        {
                            Id = 50,
                            QuantitySold = 72,
                            SaleDate = new DateTime(2024, 1, 20, 7, 29, 43, 564, DateTimeKind.Local).AddTicks(6920),
                            StoreItemId = 43,
                            SupplierId = 5,
                            TotalAmount = 122.850783147313960m
                        });
                });

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "aut",
                            Name = "Bike",
                            Price = 1.771604122021982m,
                            Quantity = 234
                        },
                        new
                        {
                            Id = 2,
                            Description = "ea",
                            Name = "Cheese",
                            Price = 1.985047052607428m,
                            Quantity = 83
                        },
                        new
                        {
                            Id = 3,
                            Description = "optio",
                            Name = "Gloves",
                            Price = 1.198489983192873m,
                            Quantity = 433
                        },
                        new
                        {
                            Id = 4,
                            Description = "doloribus",
                            Name = "Bacon",
                            Price = 1.411932913778319m,
                            Quantity = 282
                        },
                        new
                        {
                            Id = 5,
                            Description = "veniam",
                            Name = "Pants",
                            Price = 1.625375844363764m,
                            Quantity = 132
                        },
                        new
                        {
                            Id = 6,
                            Description = "in",
                            Name = "Pizza",
                            Price = 1.838818774949209m,
                            Quantity = 481
                        },
                        new
                        {
                            Id = 7,
                            Description = "accusamus",
                            Name = "Shirt",
                            Price = 1.0522617055346545m,
                            Quantity = 331
                        },
                        new
                        {
                            Id = 8,
                            Description = "dolorem",
                            Name = "Salad",
                            Price = 1.2657046361201m,
                            Quantity = 180
                        },
                        new
                        {
                            Id = 9,
                            Description = "praesentium",
                            Name = "Table",
                            Price = 1.479147566705545m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            Description = "facere",
                            Name = "Sausages",
                            Price = 1.69259049729099m,
                            Quantity = 379
                        },
                        new
                        {
                            Id = 11,
                            Description = "quae",
                            Name = "Shoes",
                            Price = 1.906033427876436m,
                            Quantity = 229
                        },
                        new
                        {
                            Id = 12,
                            Description = "laboriosam",
                            Name = "Chips",
                            Price = 1.119476358461881m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 13,
                            Description = "harum",
                            Name = "Hat",
                            Price = 1.332919289047327m,
                            Quantity = 428
                        },
                        new
                        {
                            Id = 14,
                            Description = "molestiae",
                            Name = "Chair",
                            Price = 1.546362219632772m,
                            Quantity = 277
                        },
                        new
                        {
                            Id = 15,
                            Description = "eius",
                            Name = "Towels",
                            Price = 1.759805150218217m,
                            Quantity = 127
                        },
                        new
                        {
                            Id = 16,
                            Description = "excepturi",
                            Name = "Computer",
                            Price = 1.973248080803662m,
                            Quantity = 476
                        },
                        new
                        {
                            Id = 17,
                            Description = "aut",
                            Name = "Soap",
                            Price = 1.186691011389108m,
                            Quantity = 326
                        },
                        new
                        {
                            Id = 18,
                            Description = "aspernatur",
                            Name = "Keyboard",
                            Price = 1.400133941974553m,
                            Quantity = 175
                        },
                        new
                        {
                            Id = 19,
                            Description = "reprehenderit",
                            Name = "Tuna",
                            Price = 1.613576872559999m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 20,
                            Description = "nobis",
                            Name = "Mouse",
                            Price = 1.827019803145444m,
                            Quantity = 374
                        },
                        new
                        {
                            Id = 21,
                            Description = "reiciendis",
                            Name = "Chicken",
                            Price = 1.0404627337308893m,
                            Quantity = 224
                        },
                        new
                        {
                            Id = 22,
                            Description = "enim",
                            Name = "Bike",
                            Price = 1.253905664316335m,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 23,
                            Description = "error",
                            Name = "Fish",
                            Price = 1.46734859490178m,
                            Quantity = 423
                        },
                        new
                        {
                            Id = 24,
                            Description = "vero",
                            Name = "Ball",
                            Price = 1.680791525487225m,
                            Quantity = 272
                        },
                        new
                        {
                            Id = 25,
                            Description = "sequi",
                            Name = "Cheese",
                            Price = 1.894234456072671m,
                            Quantity = 122
                        },
                        new
                        {
                            Id = 26,
                            Description = "ducimus",
                            Name = "Gloves",
                            Price = 1.107677386658116m,
                            Quantity = 471
                        },
                        new
                        {
                            Id = 27,
                            Description = "quod",
                            Name = "Bacon",
                            Price = 1.321120317243561m,
                            Quantity = 321
                        },
                        new
                        {
                            Id = 28,
                            Description = "aperiam",
                            Name = "Pants",
                            Price = 1.534563247829007m,
                            Quantity = 170
                        },
                        new
                        {
                            Id = 29,
                            Description = "voluptas",
                            Name = "Salad",
                            Price = 1.748006178414452m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 30,
                            Description = "dolorum",
                            Name = "Shirt",
                            Price = 1.961449108999897m,
                            Quantity = 369
                        },
                        new
                        {
                            Id = 31,
                            Description = "repudiandae",
                            Name = "Sausages",
                            Price = 1.174892039585343m,
                            Quantity = 219
                        },
                        new
                        {
                            Id = 32,
                            Description = "quia",
                            Name = "Table",
                            Price = 1.388334970170788m,
                            Quantity = 68
                        },
                        new
                        {
                            Id = 33,
                            Description = "et",
                            Name = "Chips",
                            Price = 1.601777900756233m,
                            Quantity = 418
                        },
                        new
                        {
                            Id = 34,
                            Description = "autem",
                            Name = "Shoes",
                            Price = 1.815220831341679m,
                            Quantity = 267
                        },
                        new
                        {
                            Id = 35,
                            Description = "dicta",
                            Name = "Chair",
                            Price = 1.028663761927124m,
                            Quantity = 117
                        },
                        new
                        {
                            Id = 36,
                            Description = "vel",
                            Name = "Hat",
                            Price = 1.242106692512569m,
                            Quantity = 466
                        },
                        new
                        {
                            Id = 37,
                            Description = "tempore",
                            Name = "Car",
                            Price = 1.455549623098015m,
                            Quantity = 316
                        },
                        new
                        {
                            Id = 38,
                            Description = "delectus",
                            Name = "Towels",
                            Price = 1.66899255368346m,
                            Quantity = 165
                        },
                        new
                        {
                            Id = 39,
                            Description = "quaerat",
                            Name = "Computer",
                            Price = 1.882435484268905m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 40,
                            Description = "omnis",
                            Name = "Soap",
                            Price = 1.0958784148543507m,
                            Quantity = 364
                        },
                        new
                        {
                            Id = 41,
                            Description = "pariatur",
                            Name = "Keyboard",
                            Price = 1.309321345439796m,
                            Quantity = 214
                        },
                        new
                        {
                            Id = 42,
                            Description = "qui",
                            Name = "Chicken",
                            Price = 1.522764276025241m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 43,
                            Description = "iusto",
                            Name = "Mouse",
                            Price = 1.736207206610687m,
                            Quantity = 413
                        },
                        new
                        {
                            Id = 44,
                            Description = "qui",
                            Name = "Fish",
                            Price = 1.949650137196132m,
                            Quantity = 262
                        },
                        new
                        {
                            Id = 45,
                            Description = "voluptatem",
                            Name = "Bike",
                            Price = 1.163093067781577m,
                            Quantity = 112
                        },
                        new
                        {
                            Id = 46,
                            Description = "ipsam",
                            Name = "Cheese",
                            Price = 1.376535998367023m,
                            Quantity = 461
                        },
                        new
                        {
                            Id = 47,
                            Description = "est",
                            Name = "Ball",
                            Price = 1.589978928952468m,
                            Quantity = 311
                        },
                        new
                        {
                            Id = 48,
                            Description = "ut",
                            Name = "Bacon",
                            Price = 1.803421859537914m,
                            Quantity = 160
                        },
                        new
                        {
                            Id = 49,
                            Description = "adipisci",
                            Name = "Gloves",
                            Price = 1.0168647901233587m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 50,
                            Description = "corrupti",
                            Name = "Pizza",
                            Price = 1.230307720708804m,
                            Quantity = 359
                        });
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullAddress = "779 Grady Plains, East Georgianafort, Chad",
                            IBAN = "HR7643916023",
                            Name = "Brown and Sons"
                        },
                        new
                        {
                            Id = 2,
                            FullAddress = "00337 Feil Row, Schulistfurt, Uganda",
                            IBAN = "HR1384207005",
                            Name = "Jakubowski, Cummerata and Wyman"
                        },
                        new
                        {
                            Id = 3,
                            FullAddress = "74254 Casper Terrace, Port Jacklynport, Malta",
                            IBAN = "HR1512933586",
                            Name = "Predovic Group"
                        },
                        new
                        {
                            Id = 4,
                            FullAddress = "8386 Krajcik Spurs, North Aylin, Haiti",
                            IBAN = "HR0064472535",
                            Name = "Zboncak, Maggio and Jenkins"
                        },
                        new
                        {
                            Id = 5,
                            FullAddress = "8240 Viola Corner, Satterfieldville, Saint Barthelemy",
                            IBAN = "HR6491951930",
                            Name = "Graham - Gislason"
                        },
                        new
                        {
                            Id = 6,
                            FullAddress = "663 Micheal Street, North Edwardbury, Benin",
                            IBAN = "HR9854747175",
                            Name = "Mayert, Windler and Smitham"
                        },
                        new
                        {
                            Id = 7,
                            FullAddress = "807 Quinn Hill, Chanelport, Honduras",
                            IBAN = "HR0360988494",
                            Name = "Swaniawski - Olson"
                        },
                        new
                        {
                            Id = 8,
                            FullAddress = "48838 Verdie Turnpike, New Randy, Niger",
                            IBAN = "HR8544921716",
                            Name = "Cruickshank, Hessel and Gleason"
                        },
                        new
                        {
                            Id = 9,
                            FullAddress = "97005 Oberbrunner Parkways, New Emelyfurt, Eritrea",
                            IBAN = "HR4249905948",
                            Name = "Koch - Beer"
                        },
                        new
                        {
                            Id = 10,
                            FullAddress = "11365 Cleta Village, Vernonmouth, Thailand",
                            IBAN = "HR7234296256",
                            Name = "Rolfson, Rosenbaum and Pouros"
                        });
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("StoreId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierStoreItems");

                    b.HasData(
                        new
                        {
                            StoreId = 6,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 21,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 50,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 15,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 44,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 9,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 38,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 3,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 32,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 47,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 41,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 35,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 29,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 23,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 17,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 11,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 26,
                            SupplierId = 10
                        },
                        new
                        {
                            StoreId = 40,
                            SupplierId = 5
                        },
                        new
                        {
                            StoreId = 5,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 20,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 34,
                            SupplierId = 1
                        },
                        new
                        {
                            StoreId = 49,
                            SupplierId = 6
                        },
                        new
                        {
                            StoreId = 14,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 28,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 43,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 8,
                            SupplierId = 7
                        },
                        new
                        {
                            StoreId = 22,
                            SupplierId = 2
                        },
                        new
                        {
                            StoreId = 37,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 2,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 16,
                            SupplierId = 8
                        },
                        new
                        {
                            StoreId = 31,
                            SupplierId = 3
                        },
                        new
                        {
                            StoreId = 46,
                            SupplierId = 9
                        },
                        new
                        {
                            StoreId = 10,
                            SupplierId = 4
                        },
                        new
                        {
                            StoreId = 25,
                            SupplierId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Models.SalesRecord", b =>
                {
                    b.HasOne("Database.Models.StoreItem", "StoreItem")
                        .WithMany()
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Database.Models.SupplierStoreItem", b =>
                {
                    b.HasOne("Database.Models.StoreItem", "StoreItem")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Supplier", "Supplier")
                        .WithMany("SupplierStoreItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.StoreItem", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });

            modelBuilder.Entity("Database.Models.Supplier", b =>
                {
                    b.Navigation("SupplierStoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
